backend:
  name: github
  repo: rush2di/theke-v1
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Articles"
    folder: "static/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: titre
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - name: tags
        widget: select
        multiple: true
        min: 1
        max: 5
        options:
          [
            "science",
            "biologie",
            "astrologie",
            "literature",
            "physcique",
            "chimie",
            "technologie",
            "environnement",
            "informatique",
            "biodiversite",
            "société",
            "culture",
            "politiques",
            "décoverte",
            "exploration",
          ]
      - { label: "Coverture", name: "coverture", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "enVedette"
    label: "En vedette"
    folder: "static/vedette"
    identifier_field: selection
    create: false
    slug: "posts-en-vedette"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "en-vedette",
        }
      - name: "selection"
        label: "Selection"
        widget: "object"
        fields:
          - name: "post1"
            label: "Post 1"
            widget: "relation"
            collection: "articles"
            default: select
            searchFields: ["titre"]
            valueField: "titre"
          - name: "post2"
            label: "Post 2"
            widget: "relation"
            collection: "articles"
            default: select
            searchFields: ["titre"]
            valueField: "titre"
          - name: "post3"
            label: "Post 3"
            widget: "relation"
            collection: "articles"
            default: select
            searchFields: ["titre"]
            valueField: "titre"
