backend:
  name: github
  repo: rush2di/theke-v1
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Articles"
    folder: "static/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: titre
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "En vedette", name: "envedette", widget: "boolean" }
      - { label: "Coverture", name: "coverture", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "collectionTags",
          searchFields: ["tagName"],
          valueField: "tagName",
          multiple: true,
        }

  - name: "collectionTags"
    label: "List des tags"
    folder: "static/tagslist"
    delete: false
    editor:
      preview: false
    widget: "list"
    fields:
      - { label: "Nome du tag", name: "tagName", widget: "string" }
