backend:
  name: github
  repo: rush2di/theke-v1
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-post",
        }
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "En vedette", name: "envedette", widget: "boolean" }
      - { label: "Coverture", name: "coverture", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'relationKitchenSinkPost',
          collection: 'posts',
          searchFields: ['title', 'body'],
          valueField: 'title',
          multiple: true,
        }

  - name: 'tags'
        label: 'Tags'
        fields:
          - name: tags
            label: Tags
            widget: list
            fields:
              - { label: 'tag', name: 'tag', widget: 'string'}

