backend:
  name: github
  repo: rush2di/theke-v1
  branch: master
  locale: 'fr'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Articles"
    folder: "static/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: titre
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - name: tags
        widget: select
        multiple: true
        min: 1
        max: 5
        options:
          [
            "science",
            "biologie",
            "astrologie",
            "literature",
            "physcique",
            "chimie",
            "technologie",
            "environnement",
            "informatique",
            "biodiversite",
            "société",
            "culture",
            "politiques",
            "décoverte",
            "exploration",
          ]
      - { label: "Coverture", name: "coverture", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "enVedette"
    label: "En vedette"
    folder: "static/vedette"
    identifier_field: selection
    create: false
    slug: "posts-en-vedette"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "en-vedette",
        }
      - name: "selection"
        label: "Selection"
        widget: "object"
        fields:
          - name: "post1"
            label: "Post 1"
            widget: "relation"
            collection: "articles"
            default: select
            searchFields: ["titre"]
            valueField: "titre"
          - name: "post2"
            label: "Post 2"
            widget: "relation"
            collection: "articles"
            default: select
            searchFields: ["titre"]
            valueField: "titre"
          - name: "post3"
            label: "Post 3"
            widget: "relation"
            collection: "articles"
            default: select
            searchFields: ["titre"]
            valueField: "titre"

  - name: "apropos"
    label: "A propos"
    folder: "static/apropos"
    identifier_field: "informations"
    create: true
    slug: "a-propos"
    editor: 
      preview: false
    fields:
      - {
        name: "templateKey",
        label: "Template Key",
        widget: "hidden",
        default: "informations"
      }
      -name: "selection"
       label: "Selection"
       widget: "object"
       fields: 
        - { name: "aproposMini", label: "Description", widget: "text" }
        - { name: "telephone", label: "Numero Telephone", widget: "text" }
        - { name: "email", label: "Email Adresse", widget: "text" }
        - { name: "facebook", label: "Url Facebook", widget: "text" }
        - { name: "instagram", label: "Url Instagram", widget: "text" }
        - { name: "image1", label: "Image 1", widget: "image" }
        - { name: "paragraph1", label: "Paragraph 1", widget: "text" }
        - { name: "image2", label: "Image 2", widget: "image" }
        - { name: "paragraph2", label: "Paragraph 2", widget: "text" }